# Generated by Django 4.2.6 on 2023-10-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articlemetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('engagement_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ArticleMetadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Summaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_bad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Summaries',
                'managed': False,
            },
        ),
    ]
